# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Number of worker nodes to provision
  OKD_NODES = 2

  # Memory for the VMs
  MASTER_OKD_MEMORY = 8192
  NODE_OKD_MEMORY = 4096

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "libvirt" do |v|
      # v.memory = MEMORY
      v.cpu_mode = "host-passthrough"
  end

  # Mount ~/.ssh for provision.sh
  config.vm.synced_folder "~/.ssh/", "/.ssh",
    mount_options: ["ro"]

  # Define VMs:
  # Master
  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "master.okd.vm"
    master.vm.network "private_network", ip: "192.168.56.100", libvirt__dhcp_enabled: false
    master.vm.provider "libvirt" do |v|
      v.memory = MASTER_OKD_MEMORY
    end
  end

  # Nodes
  (1..OKD_NODES).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}.okd.vm"
      ip = 100 + i
      node.vm.network "private_network", ip: "192.168.56.#{ip}", libvirt__dhcp_enabled: false
      node.vm.provider "libvirt" do |v|
        v.memory = NODE_OKD_MEMORY
      end
    end
  end

  # Execute customer_provision.sh
  config.vm.provision "shell", path: "scripts/provision.sh"
end
